# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDistance <- function(lon1, lat1, lon2, lat2) {
    .Call('_nngeo_getDistance', PACKAGE = 'nngeo', lon1, lat1, lon2, lat2)
}

